# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19TW0kw99tlHpo34-GmWQBasJ5sbqcy3J
"""

# ================== MOUNT DRIVE ==================
# from google.colab import drive
# drive.mount('/content/drive')

# yaml_path = '/content/drive/MyDrive/data (1)/training/ball.yaml'

# # Read the content of the YAML file
# with open(yaml_path, 'r') as f:
#     yaml_content = f.read()

# print("Content of ball.yaml before correction:")
# print(yaml_content)

# # Replace the incorrect path
# corrected_yaml_content = yaml_content.replace('/content/drive/MyDrive/data/training', '/content/drive/MyDrive/data (1)/training')

# # Save the corrected content back to the YAML file
# with open(yaml_path, 'w') as f:
#     f.write(corrected_yaml_content)

# print("\nContent of ball.yaml after correction:")
# print(corrected_yaml_content)

# print("Attempting to re-run training with corrected YAML file.")

# Commented out IPython magic to ensure Python compatibility.
# %%writefile ball_hyp.yaml
# augment: true
# 
# # Color & lighting
# hsv_h: 0.015
# hsv_s: 0.3
# hsv_v: 0.4
# 
# # Geometry
# degrees: 0.0
# translate: 0.1
# scale: 0.2
# shear: 0.0
# perspective: 0.0
# flipud: 0.0
# fliplr: 0.5
# 
# # ⭐ CRITICAL FOR CRICKET BALL
# motion: 0.4
# blur: 0.3
# erasing: 0.4
# 
# # Context (keep low)
# mosaic: 0.1
# mixup: 0.0
# copy_paste: 0.0
#

from ultralytics import YOLO
import torch, os

print("CUDA available:", torch.cuda.is_available())

# ================== PATHS ==================
DATA_YAML = "/content/drive/MyDrive/data/training/ball.yaml"
SAVE_DIR  = "/content/drive/MyDrive/ball_yolo_robust"

os.makedirs(SAVE_DIR, exist_ok=True)

# ================== LOAD BASE MODEL ==================
model = YOLO("yolov8n.pt")   # fine-tuning base

# ================== TRAIN ==================
model.train(
    data=DATA_YAML,
    epochs=100,              # IMPORTANT
    imgsz=960,               # IMPORTANT (small object)
    batch=8,
    optimizer="AdamW",
    lr0=0.001,
    lrf=0.01,
    cos_lr=True,
    # hyp="ball_hyp.yaml",     # ⭐ robust augmentations
    device=0,
    project=SAVE_DIR,
    name="ball_robust",
    patience=20,
    exist_ok=True
)

print("ROBUST TRAINING DONE")